import { engineers } from '@/data/engineers'
import type { Engineer, EngineerRole, Project, ProjectRun, Rating } from './types'
const clamp=(value:number,min=0,max=100)=>Math.min(max,Math.max(min,value))
export const ratingForScore=(score:number):Rating=>score>=95?'S+':score>=88?'S':score>=80?'A':score>=70?'B':score>=60?'C':'D'
export const marketValue=(engineer:Engineer)=>{const p=(engineer.desiredSalary-engineer.transferMarketMin)/(engineer.transferMarketMax-engineer.transferMarketMin);return p<=.35?'GOOD VALUE｜割安':p<=.7?'FAIR VALUE｜適正':'PREMIUM｜割高'}
export function abilityFit(engineer:Engineer,project:Project){const d=project.demands,sum=d.deadline+d.quality+d.technicalDifficulty,a=engineer.abilities;return clamp(a.implementation*.85*d.technicalDifficulty/sum+a.speed*.85*d.deadline/sum+a.quality*.85*d.quality/sum+a.communication*.15)}
export function individualTechMatch(engineer:Engineer,project:Project){const own=project.techRequirements.filter(r=>r.role===engineer.role),cross=project.techRequirements.filter(r=>r.role!==engineer.role);const coverage=(requirements:typeof own)=>{const total=requirements.reduce((s,r)=>s+r.importance,0);return total?requirements.filter(r=>engineer.skills.includes(r.skill)).reduce((s,r)=>s+r.importance,0)/total*100:0};return clamp(coverage(own)+coverage(cross)*.1)}
export function teamTechMatch(team:Engineer[],project:Project){const roles:EngineerRole[]=['frontend','backend','infrastructure'];let weighted=0,total=0;for(const role of roles){const req=project.techRequirements.filter(r=>r.role===role),sum=req.reduce((s,r)=>s+r.importance,0);const specialists=team.filter(e=>e.role===role),pool=specialists.length?specialists:team.filter(e=>e.role!==role);const matched=req.filter(r=>pool.some(e=>e.skills.includes(r.skill))).reduce((s,r)=>s+r.importance,0);const coverage=(sum?matched/sum*100:0)*(specialists.length?1:.35);weighted+=coverage*project.requiredStrength[role];total+=project.requiredStrength[role]}return clamp(weighted/total)}
export function roleCoverage(team:Engineer[],project:Project,role:EngineerRole){const contributions=team.map(e=>abilityFit(e,project)*(e.role===role?1:.2)).sort((a,b)=>b-a);return clamp(((contributions[0]??0)+(contributions[1]??0)*.35+(contributions[2]??0)*.15)/project.requiredStrength[role]*100)}
function mulberry32(seed:number){let state=seed>>>0;return()=>{state=(state+0x6d2b79f5)>>>0;let value=state;value=Math.imul(value^(value>>>15),value|1);value^=value+Math.imul(value^(value>>>7),value|61);return((value^(value>>>14))>>>0)/4294967296}}
export const rewardMultiplier:Record<Rating,number>={'S+':1.2,S:1.1,A:1,B:.9,C:.7,D:.35}
export const ratingBonus:Record<Rating,number>={'S+':350,S:300,A:220,B:140,C:60,D:0}
export const headcountFactor=(count:number)=>count===3?1:count===2?.82:count===1?.6:0
export const rewardForRating=(baseReward:number,rating:Rating)=>Math.round(baseReward*rewardMultiplier[rating])
export const budgetGrowthForResult=(actualReward:number,rating:Rating)=>Math.min(500,ratingBonus[rating]+Math.floor(actualReward*.05/10)*10)
export function evaluateProject(project:Project,team:Engineer[],salaryBudget:number,seed:number):ProjectRun{const roles:EngineerRole[]=['frontend','backend','infrastructure'];const strengthTotal=roles.reduce((s,r)=>s+project.requiredStrength[r],0);const coverage=roles.reduce((s,r)=>s+roleCoverage(team,project,r)*project.requiredStrength[r],0)/strengthTotal;const tech=teamTechMatch(team,project);const ability=team.reduce((s,e)=>s+abilityFit(e,project),0)/team.length;const random=mulberry32(seed),adjustment=Math.floor(random()*21)-10,individuals=[0,1,2].map(()=>Math.floor(random()*11)-5);const score=clamp((coverage*.4+tech*.35+ability*.25)*headcountFactor(team.length)+adjustment);const rating=ratingForScore(score),actualReward=rewardForRating(project.baseReward,rating);const growth=budgetGrowthForResult(actualReward,rating);const avg=(key:keyof Engineer['abilities'])=>team.reduce((s,e)=>s+e.abilities[key],0)/team.length;const performances=Object.fromEntries(team.map((e,i)=>[e.id,clamp(abilityFit(e,project)*.55+individualTechMatch(e,project)*.3+project.requiredStrength[e.role]*.15+individuals[i])])) as Record<string,number>;return{projectId:project.id,teamEngineerIds:team.map(e=>e.id),salaryBudgetAtStart:salaryBudget,teamCostAtStart:team.reduce((s,e)=>s+e.desiredSalary,0),randomSeed:seed,projectScore:score,rating,success:score>=60,deadlineScore:clamp(avg('speed')*.55+coverage*.25+tech*.2+adjustment*.5),qualityScore:clamp(avg('quality')*.55+avg('implementation')*.25+tech*.2+adjustment*.3),stabilityScore:clamp(roleCoverage(team,project,'infrastructure')*.4+avg('quality')*.3+tech*.2+avg('communication')*.1+adjustment*.3),teamTechMatch:tech,actualReward,salaryBudgetGrowth:growth,engineerPerformances:performances}}
export function companyMetrics(runs:ProjectRun[]){const average=(values:number[])=>values.reduce((s,v)=>s+v,0)/values.length,averageProjectScore=average(runs.map(r=>r.projectScore)),rewardScore=clamp(runs.reduce((s,r)=>s+r.actualReward,0)/5000*100),costEfficiencyScore=average(runs.map(r=>clamp(r.projectScore+(1-r.teamCostAtStart/r.salaryBudgetAtStart)*25))),averageTechMatch=average(runs.map(r=>r.teamTechMatch)),companyIndex=averageProjectScore*.4+rewardScore*.2+costEfficiencyScore*.2+averageTechMatch*.2;return{averageProjectScore,averageTechMatch,companyIndex,leaguePoints:Math.round(companyIndex*100),ceoRating:ratingForScore(companyIndex)}}
export function bestEngineer(runs:ProjectRun[]){const candidates=engineers.filter(e=>runs.some(r=>r.teamEngineerIds.includes(e.id))).map(e=>{const values=runs.filter(r=>r.engineerPerformances[e.id]!==undefined).map(r=>r.engineerPerformances[e.id]);return{engineer:e,average:values.reduce((s,v)=>s+v,0)/values.length,appearances:values.length}});return candidates.sort((a,b)=>b.average-a.average||b.appearances-a.appearances||b.engineer.ovr-a.engineer.ovr||engineers.indexOf(a.engineer)-engineers.indexOf(b.engineer))[0]}
export const competitionRank=(points:number,allPoints:number[])=>1+allPoints.filter(value=>value>points).length
export function projectMvp(run:ProjectRun){return engineers.filter(engineer=>run.teamEngineerIds.includes(engineer.id)).sort((a,b)=>run.engineerPerformances[b.id]-run.engineerPerformances[a.id]||b.ovr-a.ovr||engineers.indexOf(a)-engineers.indexOf(b))[0]}
