'use client'
import { useEffect, useRef, useState } from 'react'
import { engineers } from '@/data/engineers'
import { competitors, projects } from '@/data/projects'
import { bestEngineer, companyMetrics, competitionRank, individualTechMatch, marketValue, projectMvp, ratingForScore, teamTechMatch } from '@/domain/calculations'
import { INITIAL_STATE, type Engineer, type GameState, type Project } from '@/domain/types'
import { CompanyNameSchema } from '@/shared/schemas/game-state.schema'
import { loadGameState, resetGameState, saveGameState } from '@/adapters/repositories/local-storage-game-state-repository'
import { completeRetention, hireEngineer, releaseEngineer, retainEngineer, revealResult, selectProject, startProject, teamCost } from '@/usecases/game-actions'

type Tab='club'|'market'|'projects'
const roleLabel={frontend:'Frontend',backend:'Backend',infrastructure:'Infrastructure'}
function Avatar({engineer}:{engineer:Engineer}){return <div className={`avatar avatar-${engineer.id}`} role="img" aria-label={`${engineer.name}の架空アバター`}><span>{engineer.name.replace(' ','').slice(-1)}</span></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const dialogRef=useRef<HTMLElement>(null),previousFocus=useRef<HTMLElement|null>(null);useEffect(()=>{previousFocus.current=document.activeElement as HTMLElement;const dialog=dialogRef.current;dialog?.querySelector<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled)')?.focus();return()=>previousFocus.current?.focus()},[]);const handleKeyDown=(event:React.KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();onClose();return}if(event.key!=='Tab')return;const focusable=[...(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), [tabindex]:not([tabindex="-1"])')??[])];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section ref={dialogRef} className="modal" role="dialog" aria-modal="true" aria-label={title} onKeyDown={handleKeyDown}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="閉じる">×</button></header>{children}</section></div>}
function TeamFormation({state,project,onEngineer}:{state:GameState;project:Project;onEngineer:(e:Engineer)=>void}){return <section className="formation" aria-label="My Team"><div className="formation-label"><span>MY TEAM</span><strong>{state.teamEngineerIds.length} / 3</strong></div><div className="pitch">{project.recommendedSlots.map((role,index)=>{const e=engineers.find(x=>x.id===state.teamEngineerIds[index]);return <button key={index} className={`team-slot slot-${index}`} onClick={()=>e&&onEngineer(e)} disabled={!e}><small>{roleLabel[role]}</small>{e?<><span className="mini-avatar">{e.name.slice(-1)}</span><strong>{e.name}</strong><em>OVR {e.ovr}</em></>:<strong>EMPTY</strong>}</button>})}</div></section>}
function EngineerDetail({engineer,match,onClose,onHire,onRelease,disabled}:{engineer:Engineer;match:number;onClose:()=>void;onHire:()=>void;onRelease?:()=>void;disabled:string|null}){return <Modal title={engineer.name} onClose={onClose}><div className={`detail-hero rarity-${engineer.rarity.toLowerCase()}`}><Avatar engineer={engineer}/><div><span className="rarity">{engineer.rarity}</span><strong className="ovr">{engineer.ovr}</strong><p>{engineer.title}</p></div></div><div className="detail-grid"><span>案件適合<strong>{Math.round(match)}%</strong></span><span>市場評価<strong>{'★'.repeat(engineer.marketRating)}</strong></span><span>移籍市場<strong>{engineer.transferMarketMin}〜{engineer.transferMarketMax}万円</strong></span><span>希望年俸<strong>{engineer.desiredSalary}万円</strong></span></div><p className="value">{marketValue(engineer)}</p><div className="skills">{engineer.skills.map(s=><span key={s}>{s}</span>)}</div><div className="abilities">{Object.entries(engineer.abilities).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{onRelease?<button className="danger reset" onClick={onRelease}>放出する</button>:<button className="primary" disabled={!!disabled} onClick={onHire}>{disabled??'獲得する'}</button>}</Modal>}
function ProjectDetail({project,onClose,onSelect,disabled}:{project:Project;onClose:()=>void;onSelect:()=>void;disabled:boolean}){return <Modal title={project.name} onClose={onClose}><p className="eyebrow">DIVISION {project.division} · {'★'.repeat(project.difficulty)}</p><div className="stat-row"><span>基本報酬<strong>{project.baseReward}万円</strong></span><span>納期<strong>{project.demands.deadline}</strong></span><span>品質<strong>{project.demands.quality}</strong></span><span>技術<strong>{project.demands.technicalDifficulty}</strong></span></div><h3>必要戦力</h3><div className="strength">FE {project.requiredStrength.frontend} · BE {project.requiredStrength.backend} · INFRA {project.requiredStrength.infrastructure}</div><h3>推奨3スロット</h3><div className="strength">{project.recommendedSlots.map(role=>roleLabel[role]).join(' · ')}</div><h3>推奨技術</h3><div className="requirements">{project.techRequirements.map(r=><div key={r.skill}><span>{r.skill}</span><strong>{r.importance}</strong></div>)}</div><button className="primary" disabled={disabled} onClick={onSelect}>{disabled?'完了済み':'この案件を選ぶ'}</button></Modal>}

export default function GameApp(){
 const [state,setState]=useState<GameState>(INITIAL_STATE),[hydrated,setHydrated]=useState(false),[persistenceEnabled,setPersistenceEnabled]=useState(false),[notice,setNotice]=useState<string|null>(null),[tab,setTab]=useState<Tab>('projects'),[modalEngineer,setModalEngineer]=useState<Engineer|null>(null),[modalProject,setModalProject]=useState<Project|null>(null),[company,setCompany]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('match'),[confirmHire,setConfirmHire]=useState<Engineer|null>(null),[confirmStart,setConfirmStart]=useState(false),[signing,setSigning]=useState<Engineer|null>(null)
 useEffect(()=>{const loaded=loadGameState(window.localStorage);setState(loaded.state);setNotice(loaded.notice);setPersistenceEnabled(loaded.persistenceEnabled);if(['RETENTION_DECISION','TEAM_2_BUILD'].includes(loaded.state.phase))setTab('club');setHydrated(true)},[])
 useEffect(()=>{if(hydrated&&persistenceEnabled){const error=saveGameState(window.localStorage,state);if(error){setNotice(error);setPersistenceEnabled(false)}}},[state,hydrated,persistenceEnabled])
 const project=projects.find(p=>p.id===state.selectedProjectId)??null,cost=teamCost(state),remaining=state.annualSalaryBudget-cost
 const update=(next:GameState)=>setState(next)
 const establish=()=>{const parsed=CompanyNameSchema.safeParse(company);if(parsed.success){update({...INITIAL_STATE,companyName:parsed.data,phase:'PROJECT_1_SELECT'});setTab('projects')}}
 if(!hydrated)return <main className="loading">Loading club…</main>
 if(state.phase==='COMPANY_SETUP')return <main className="setup"><div className="brand-mark">TTM</div><p className="eyebrow">TECH TRANSFER MARKET</p><h1>Build your<br/>engineering club.</h1><p className="lead">技術と才能を見極め、最高の3人を市場から獲得しよう。</p><label>COMPANY NAME<input value={company} maxLength={31} onChange={e=>setCompany(e.target.value)} placeholder="会社名を入力"/></label><p className="storage-note">ゲームデータはこの端末・ブラウザ内に保存されます。<br/>ブラウザデータの削除や端末変更などにより、<br/>データが失われる場合があります。</p><button className="primary" disabled={!CompanyNameSchema.safeParse(company).success} onClick={establish}>会社を設立する</button>{notice&&<div className="notice">{notice}</div>}</main>
 if(state.phase.startsWith('DEVELOPMENT'))return <Development state={state} onDone={()=>update(revealResult(state))}/>
 if(state.phase.startsWith('RESULT'))return <Result state={state} onNext={()=>{if(state.phase==='RESULT_1'){update({...state,phase:'PROJECT_2_SELECT',selectedProjectId:null});setTab('projects')}else update({...state,phase:'SEASON_COMPLETE'})}}/>
 if(state.phase==='SEASON_COMPLETE')return <Season state={state} onReset={()=>{if(confirm('シーズンデータを削除して最初からやり直しますか？')){const error=resetGameState(window.localStorage);if(error){setNotice(error);setPersistenceEnabled(false)}setState({...INITIAL_STATE});setCompany('')}}}/>
 const inRetention=state.phase==='RETENTION_DECISION',runOne=state.projectRuns[0],retentionDone=!inRetention||runOne.teamEngineerIds.every(id=>state.retentionDecisions[id])
 const list=engineers.filter(e=>!state.teamEngineerIds.includes(e.id)&&!state.releasedEngineerIds.includes(e.id)&&(filter==='all'||e.role===filter)).map((e,index)=>({e,index,match:project?individualTechMatch(e,project):0})).sort((a,b)=>sort==='ovr'?b.e.ovr-a.e.ovr||a.index-b.index:sort==='salary'?a.e.desiredSalary-b.e.desiredSalary||a.index-b.index:sort==='rating'?b.e.marketRating-a.e.marketRating||a.index-b.index:b.match-a.match||a.index-b.index)
 const hireDisabled=(e:Engineer)=>state.teamEngineerIds.length>=3?'チーム満員':e.desiredSalary>remaining?`あと${e.desiredSalary-remaining}万円不足`:null
 const choose=(p:Project)=>{const apply=()=>{update(selectProject(state,p.id));setModalProject(null);setTab(state.projectRuns.length?'club':'market')};if(state.selectedProjectId&&state.selectedProjectId!==p.id&&!confirm('選択中の案件を変更しますか？\n獲得済みのチームは維持されます。'))return;apply()}
 return <div className="app-shell"><header className="topbar"><div><small>{state.projectRuns.length?'PROJECT 2 / 2':'PROJECT 1 / 2'}</small><strong>{state.companyName}</strong></div><div className="budget"><small>残り年俸枠</small><strong>{remaining.toLocaleString()}万円</strong></div></header>{notice&&<div className="notice floating">{notice}</div>}
  <main className="content">
   {tab==='projects'&&<section><div className="page-title"><p className="eyebrow">PROJECT BOARD</p><h1>次の挑戦を選ぶ。</h1><p>5つの案件から、チームの未来を決めよう。</p></div><div className="project-list">{projects.map(p=><button className="project-card" key={p.id} disabled={state.completedProjectIds.includes(p.id)} onClick={()=>setModalProject(p)}><span className="division">DIV {p.division}</span><h2>{p.name}</h2><p>{p.techRequirements.slice(0,3).map(r=>r.skill).join(' / ')}</p><strong>{p.baseReward.toLocaleString()}万円</strong>{state.selectedProjectId===p.id&&<em>SELECTED</em>}{state.completedProjectIds.includes(p.id)&&<em>COMPLETED</em>}</button>)}</div></section>}
   {tab==='club'&&project&&<section><div className="page-title"><p className="eyebrow">CLUB HOUSE</p><h1>{inRetention?'残すか、託すか。':'Ready for kickoff?'}</h1><p>{project.name} · Tech Match {Math.round(teamTechMatch(engineers.filter(e=>state.teamEngineerIds.includes(e.id)),project))}%</p></div><TeamFormation state={state} project={project} onEngineer={setModalEngineer}/>{inRetention&&<div className="retention"><h2>RETENTION DECISION</h2>{runOne.teamEngineerIds.map(id=>{const e=engineers.find(x=>x.id===id)!;return <div className="retention-row" key={id}><div><strong>{e.name}</strong><small>前回 {Math.round(runOne.engineerPerformances[id])} · 次案件 {Math.round(individualTechMatch(e,project))}%</small></div><button className={state.retentionDecisions[id]==='retain'?'selected':''} onClick={()=>update(retainEngineer(state,id))}>残留</button><button className={state.retentionDecisions[id]==='release'?'danger selected':'danger'} onClick={()=>update(releaseEngineer(state,id))}>放出</button></div>})}<button className="primary" disabled={!retentionDone} onClick={()=>update(completeRetention(state))}>判断を確定する</button></div>}{!inRetention&&<><div className="club-stats"><span>会社資金<strong>{state.companyCash.toLocaleString()}万円</strong></span><span>年間枠<strong>{state.annualSalaryBudget.toLocaleString()}万円</strong></span><span>使用中<strong>{cost.toLocaleString()}万円</strong></span></div><button className="primary" disabled={!state.teamEngineerIds.length} onClick={()=>setConfirmStart(true)}>開発開始</button></>}</section>}
   {tab==='market'&&project&&<section className="market"><div className="market-summary"><p className="eyebrow">TRANSFER MARKET</p><h1>{project.name}</h1><p>{project.techRequirements.slice(0,3).map(r=>r.skill).join(' / ')}</p><TeamFormation state={state} project={project} onEngineer={setModalEngineer}/><div className="salary-line"><span>{cost.toLocaleString()} / {state.annualSalaryBudget.toLocaleString()}万円</span><strong>残り {remaining.toLocaleString()}万円</strong></div></div><div className="compact-sticky">{project.name} <span>Match {Math.round(teamTechMatch(engineers.filter(e=>state.teamEngineerIds.includes(e.id)),project))}% · {cost}/{state.annualSalaryBudget}万円 · {state.teamEngineerIds.length}/3人</span></div><div className="market-controls"><div>{['all','frontend','backend','infrastructure'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f==='all'?'ALL':roleLabel[f as keyof typeof roleLabel]}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="並び替え"><option value="match">案件適合: 高い順</option><option value="ovr">OVR: 高い順</option><option value="salary">希望年俸: 安い順</option><option value="rating">市場評価: 高い順</option></select></div><div className="engineer-list">{list.map(({e,match})=><article className={`engineer-card rarity-${e.rarity.toLowerCase()}`} key={e.id} onClick={()=>setModalEngineer(e)}><div className="visual"><div><span className="rarity">{e.rarity}</span><strong className="ovr">{e.ovr}</strong><small>OVR</small></div><Avatar engineer={e}/><div className="identity"><h2>{e.name}</h2><p>{e.title}</p></div></div><div className="decision"><div className="chips">{e.skills.slice(0,3).map(s=><span key={s}>{s}</span>)}</div><div className="match"><span>案件適合<strong>{Math.round(match)}%</strong></span><span>市場評価<strong>{'★'.repeat(e.marketRating)}</strong></span></div><p>移籍市場 {e.transferMarketMin}〜{e.transferMarketMax}万円</p><p>希望年俸 <strong>{e.desiredSalary}万円</strong></p><div className="card-action"><span className="value">{marketValue(e)}</span><button disabled={!!hireDisabled(e)} onClick={ev=>{ev.stopPropagation();setConfirmHire(e)}}>{hireDisabled(e)??'獲得する'}</button></div></div></article>)}</div></section>}
   {tab==='market'&&!project&&<div className="empty"><h1>案件を先に選択してください</h1><button className="primary" onClick={()=>setTab('projects')}>PROJECTSへ</button></div>}
  </main><nav className="bottom-nav" aria-label="メインナビゲーション"><button className={tab==='club'?'active':''} onClick={()=>setTab('club')}>CLUB</button><button className={`market-tab ${tab==='market'?'active':''}`} disabled={!project||inRetention} onClick={()=>setTab('market')}>MARKET</button><button className={tab==='projects'?'active':''} onClick={()=>setTab('projects')}>PROJECTS</button></nav>
  {modalProject&&<ProjectDetail project={modalProject} disabled={state.completedProjectIds.includes(modalProject.id)} onClose={()=>setModalProject(null)} onSelect={()=>choose(modalProject)}/>} {modalEngineer&&project&&<EngineerDetail engineer={modalEngineer} match={individualTechMatch(modalEngineer,project)} disabled={state.teamEngineerIds.includes(modalEngineer.id)?'所属中':hireDisabled(modalEngineer)} onClose={()=>setModalEngineer(null)} onHire={()=>{setConfirmHire(modalEngineer);setModalEngineer(null)}} onRelease={state.teamEngineerIds.includes(modalEngineer.id)&&!runOne?.teamEngineerIds.includes(modalEngineer.id)?()=>{if(confirm(`${modalEngineer.name}を放出しますか？`)){update(releaseEngineer(state,modalEngineer.id));setModalEngineer(null)}}:undefined}/>}
  {confirmHire&&<Modal title="獲得確認" onClose={()=>setConfirmHire(null)}><p><strong>{confirmHire.name}</strong>を獲得しますか？</p><div className="confirm-lines"><span>希望年俸 {confirmHire.desiredSalary}万円</span><span>残り人件費枠 {remaining-confirmHire.desiredSalary}万円</span></div><button className="primary" onClick={()=>{update(hireEngineer(state,confirmHire.id));setSigning(confirmHire);setConfirmHire(null);setTimeout(()=>setSigning(null),1800)}}>獲得する</button></Modal>}
  {confirmStart&&project&&<Modal title={state.teamEngineerIds.length<3?'チームが3人揃っていません':'開発開始'} onClose={()=>setConfirmStart(false)}><p>{state.teamEngineerIds.length<3?'成功率が大きく下がります。':'このチームで開発を開始しますか？'}</p><div className="confirm-lines"><span>案件: {project.name}</span><span>チームコスト: {cost} / {state.annualSalaryBudget}万円</span><span>技術マッチ: {Math.round(teamTechMatch(engineers.filter(e=>state.teamEngineerIds.includes(e.id)),project))}%</span></div><button className="primary" onClick={()=>{const seed=crypto.getRandomValues(new Uint32Array(1))[0];update(startProject(state,seed));setConfirmStart(false)}}>{state.teamEngineerIds.length<3?'このまま開始':'開発開始'}</button></Modal>}
  {signing&&<div className={`signing ${signing.rarity==='STAR'||signing.rarity==='ELITE'?'special':''}`}><span>NEW SIGNING</span><strong>{signing.rarity} · OVR {signing.ovr}</strong><h2>{signing.name}</h2></div>}
 </div>
}

function Development({state,onDone}:{state:GameState;onDone:()=>void}){const [step,setStep]=useState(0),labels=['Building…','Testing…','Deploying…','PROJECT COMPLETE'],onDoneRef=useRef(onDone);useEffect(()=>{onDoneRef.current=onDone},[onDone]);useEffect(()=>{const timers=[900,1800,2700,3600].map((ms,i)=>setTimeout(()=>i===3?onDoneRef.current():setStep(i+1),ms));return()=>timers.forEach(clearTimeout)},[]);return <main className="development"><p className="eyebrow">DEVELOPMENT</p><div className="development-orbit"><span>{step+1}</span></div><h1>{labels[step]}</h1><div className="steps">{labels.slice(0,3).map((l,i)=><span className={i<=step?'done':''} key={l}>{l.replace('…','')}</span>)}</div><small>Project random seed secured · {state.projectRuns.at(-1)?.randomSeed}</small></main>}
function Result({state,onNext}:{state:GameState;onNext:()=>void}){const reducedMotion=typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;const [revealStep,setRevealStep]=useState(reducedMotion?4:0),run=state.projectRuns.at(-1)!;const project=projects.find(p=>p.id===run.projectId)!,mvp=projectMvp(run);useEffect(()=>{if(reducedMotion)return;const timers=[200,400,600,800].map((ms,index)=>setTimeout(()=>setRevealStep(index+1),ms));return()=>timers.forEach(clearTimeout)},[reducedMotion]);return <main className="result"><section className="result-reveal"><p className="eyebrow">{run.success?'PROJECT COMPLETE':'PROJECT FAILED'}</p><div className="rating">{run.rating}</div><h1>{project.name}</h1><p className="score">FINAL SCORE {Math.round(run.projectScore)} · TECH MATCH {Math.round(run.teamTechMatch)}%</p></section>{revealStep>=1&&<section className="reward result-reveal"><span>基本報酬<strong>{project.baseReward.toLocaleString()}万円</strong></span><span>実獲得報酬<strong>+{run.actualReward.toLocaleString()}万円</strong></span><span>Team Cost<strong>{run.teamCostAtStart.toLocaleString()}万円</strong></span><span>会社資金<strong>{(state.companyCash-run.actualReward).toLocaleString()} → {state.companyCash.toLocaleString()}万円</strong></span><span>年間人件費枠<strong>{(state.annualSalaryBudget-run.salaryBudgetGrowth).toLocaleString()} → {state.annualSalaryBudget.toLocaleString()}万円</strong></span></section>}{revealStep>=2&&<section className="result-scores result-reveal">{[['納期',run.deadlineScore],['品質',run.qualityScore],['安定性',run.stabilityScore]].map(([label,value])=><div key={label as string}><span>{label}</span><strong>{ratingForScore(value as number)}</strong><small>{Math.round(value as number)}</small></div>)}</section>}{revealStep>=3&&<section className="mvp result-reveal"><span>MVP ENGINEER</span><h2>{mvp.name}</h2><p>Performance {Math.round(run.engineerPerformances[mvp.id])}</p></section>}{revealStep>=4&&<><section className="performances result-reveal">{run.teamEngineerIds.map(id=>{const e=engineers.find(x=>x.id===id)!;return <article key={id}><strong>{e.name} · {roleLabel[e.role]}</strong><span>{Math.round(run.engineerPerformances[id])}</span><small>案件適合 {Math.round(individualTechMatch(e,project))}%</small><p>{individualTechMatch(e,project)>=85?'案件技術との相性が高く、専門領域で大きく貢献。':run.engineerPerformances[id]<65?'案件要件に対して適合度が不足し、期待した成果を出し切れなかった。':'持ち味を発揮し、チームの成果に堅実に貢献。'}</p></article>})}</section><button className="primary result-reveal" onClick={onNext}>{state.phase==='RESULT_1'?'次の案件を選ぶ':'シーズン結果を見る'}</button></>}</main>}
function Season({state,onReset}:{state:GameState;onReset:()=>void}){const metrics=companyMetrics(state.projectRuns),best=bestEngineer(state.projectRuns),ranking=[...competitors.map((c,i)=>({...c,seed:i,isUser:false})),{name:state.companyName!,points:metrics.leaguePoints,seed:99,isUser:true}].sort((a,b)=>b.points-a.points||Number(a.isUser)-Number(b.isUser)||a.seed-b.seed),allPoints=ranking.map(company=>company.points),rank=competitionRank(metrics.leaguePoints,allPoints),successes=state.projectRuns.filter(run=>run.success).length;return <main className="season"><p className="eyebrow">SEASON COMPLETE</p><div className="season-rank"><small>FINAL RANK</small><strong>{rank}</strong><span>/ 10</span></div><h1>{state.companyName}</h1><div className="season-summary"><span>CEO RATING<strong>{metrics.ceoRating}</strong></span><span>BEST ENGINEER<strong>{best.engineer.name}</strong></span><span>SUCCESS / FAILED<strong>{successes} / {2-successes}</strong></span><span>総獲得報酬<strong>{state.projectRuns.reduce((s,r)=>s+r.actualReward,0)}万円</strong></span><span>最終会社資金<strong>{state.companyCash}万円</strong></span><span>最終年間人件費枠<strong>{state.annualSalaryBudget}万円</strong></span><span>平均PROJECT SCORE<strong>{Math.round(metrics.averageProjectScore)}</strong></span><span>平均TECH MATCH<strong>{Math.round(metrics.averageTechMatch)}%</strong></span></div><section className="league"><h2>LEAGUE TABLE</h2>{ranking.map(company=><div className={company.isUser?'you':''} key={company.name}><span>{competitionRank(company.points,allPoints)}</span><strong>{company.name}</strong><em>{company.points} PTS</em></div>)}</section><button className="danger reset" onClick={onReset}>最初からやり直す</button></main>}
