import { describe, expect, it } from 'vitest'
import { INITIAL_STATE } from '@/domain/types'
import { GameStateSchema } from '@/shared/schemas/game-state.schema'
import { completeRetention, hireEngineer, releaseEngineer, retainEngineer, revealResult, selectProject, startProject, teamCost } from './game-actions'
describe('ゲーム進行',()=>{
 const company={...INITIAL_STATE,companyName:'Test Club',phase:'PROJECT_1_SELECT' as const}
 it('Projectを選択したとき、Team Buildへ遷移すること',()=>expect(selectProject(company,'project-01').phase).toBe('TEAM_1_BUILD'))
 it('Projectを変更したとき、獲得済みTeamが維持されること',()=>{const state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03']};expect(selectProject(state,'project-02').teamEngineerIds).toEqual(['fe-03'])})
 it('Engineerを獲得したとき、空き枠へ追加され年俸枠を消費すること',()=>{const state=hireEngineer(selectProject(company,'project-01'),'fe-03');expect(state.teamEngineerIds).toEqual(['fe-03']);expect(teamCost(state)).toBe(680)})
 it('年俸枠を超えるEngineerを獲得しようとしたとき、加入しないこと',()=>{const state={...selectProject(company,'project-01'),annualSalaryBudget:100};expect(hireEngineer(state,'fe-01').teamEngineerIds).toHaveLength(0)})
 it('3人所属しているとき、新しいEngineerを獲得できないこと',()=>{const state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03','be-04','infra-05']};expect(hireEngineer(state,'fe-05')).toBe(state)})
 it('Engineerを放出したとき、年俸枠が戻りMarketから除外されること',()=>{const state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03']};const released=releaseEngineer(state,'fe-03');expect(released.teamEngineerIds).toHaveLength(0);expect(released.releasedEngineerIds).toContain('fe-03')})
 it('Project開始を確定したとき、Random Seedが1回だけ保存されること',()=>{const state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03','be-04']};const started=startProject(state,99);expect(started.projectRuns[0].randomSeed).toBe(99);expect(started.phase).toBe('DEVELOPMENT_1')})
 it('0人のとき、Project開始できないこと',()=>{const state=selectProject(company,'project-01');expect(startProject(state,1)).toBe(state)})
 it('Project開始を確定したとき、Team Slot配列順がProjectRunへ保存されること',()=>{const state={...selectProject(company,'project-01'),teamEngineerIds:['infra-05','fe-03','be-04']};expect(startProject(state,99).projectRuns[0].teamEngineerIds).toEqual(state.teamEngineerIds)})
 it('Retention Decisionが未完了のとき、Marketから補強できないこと',()=>{const state={...company,phase:'RETENTION_DECISION' as const,selectedProjectId:'project-02',teamEngineerIds:['fe-03'],retentionDecisions:{},projectRuns:[]};expect(hireEngineer(state,'be-04')).toBe(state)})
 it('1案件目で増えた人件費枠が2案件目補強で即時利用できること',()=>{let state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03','be-04','infra-05']};state=revealResult(startProject(state,1));state={...releaseEngineer(state,'infra-05'),phase:'TEAM_2_BUILD',selectedProjectId:'project-02',retentionDecisions:{'fe-03':'retain','be-04':'retain','infra-05':'release'}};const budgetAfterProject=state.annualSalaryBudget;state=hireEngineer(state,'infra-03');expect(budgetAfterProject).toBeGreaterThan(2000);expect(state.teamEngineerIds).toContain('infra-03')})
 it('残留判断を完了したとき、2案件目Team Buildへ進むこと',()=>{const state={...company,phase:'RETENTION_DECISION' as const,teamEngineerIds:['fe-03'],retentionDecisions:{},projectRuns:[]};expect(completeRetention(retainEngineer(state,'fe-03')).phase).toBe('TEAM_2_BUILD')})
 it('放出後に残留へ判断変更したとき、Teamへ復帰してReleasedから除外されること',()=>{const state={...company,phase:'RETENTION_DECISION' as const,teamEngineerIds:['fe-03'],retentionDecisions:{},projectRuns:[]};const restored=retainEngineer(releaseEngineer(state,'fe-03'),'fe-03');expect(restored.teamEngineerIds).toContain('fe-03');expect(restored.releasedEngineerIds).not.toContain('fe-03')})
 it('主要Flowを進めたとき、2案件を完了してSeason結果に必要なStateが成立すること',()=>{let state={...selectProject(company,'project-01'),teamEngineerIds:['fe-03','be-04','infra-05']};state=startProject(state,1);state=revealResult(state);state={...state,phase:'PROJECT_2_SELECT',selectedProjectId:null};state=selectProject(state,'project-02');for(const id of state.projectRuns[0].teamEngineerIds)state=retainEngineer(state,id);state=completeRetention(state);state=startProject(state,2);state=revealResult(state);state={...state,phase:'SEASON_COMPLETE'};expect(state.projectRuns).toHaveLength(2);expect(state.completedProjectIds).toHaveLength(2);expect(state.companyCash).toBeGreaterThan(0);expect(GameStateSchema.safeParse(state).success).toBe(true)})
})
