import { engineers } from '@/data/engineers'
import { projects } from '@/data/projects'
import { evaluateProject } from '@/domain/calculations'
import type { GameState } from '@/domain/types'
export const teamCost=(state:GameState)=>state.teamEngineerIds.reduce((sum,id)=>sum+(engineers.find(e=>e.id===id)?.desiredSalary??0),0)
export function selectProject(state:GameState,projectId:string):GameState{if(state.completedProjectIds.includes(projectId))return state;return{...state,selectedProjectId:projectId,phase:state.projectRuns.length?'RETENTION_DECISION':'TEAM_1_BUILD',retentionDecisions:state.projectRuns.length?{}:state.retentionDecisions}}
export function hireEngineer(state:GameState,engineerId:string):GameState{const engineer=engineers.find(e=>e.id===engineerId);if(state.phase==='RETENTION_DECISION'||!engineer||state.teamEngineerIds.length>=3||state.releasedEngineerIds.includes(engineerId)||teamCost(state)+engineer.desiredSalary>state.annualSalaryBudget)return state;return{...state,teamEngineerIds:[...state.teamEngineerIds,engineerId]}}
export function releaseEngineer(state:GameState,engineerId:string):GameState{return{...state,teamEngineerIds:state.teamEngineerIds.filter(id=>id!==engineerId),releasedEngineerIds:[...new Set([...state.releasedEngineerIds,engineerId])],retentionDecisions:{...state.retentionDecisions,[engineerId]:'release'}}}
export function retainEngineer(state:GameState,engineerId:string):GameState{if(!state.teamEngineerIds.includes(engineerId)&&state.teamEngineerIds.length>=3)return state;return{...state,teamEngineerIds:state.teamEngineerIds.includes(engineerId)?state.teamEngineerIds:[...state.teamEngineerIds,engineerId],releasedEngineerIds:state.releasedEngineerIds.filter(id=>id!==engineerId),retentionDecisions:{...state.retentionDecisions,[engineerId]:'retain'}}}
export function completeRetention(state:GameState):GameState{return{...state,phase:'TEAM_2_BUILD'}}
export function startProject(state:GameState,seed:number):GameState{const project=projects.find(p=>p.id===state.selectedProjectId),team=state.teamEngineerIds.map(id=>engineers.find(e=>e.id===id)).filter((engineer):engineer is NonNullable<typeof engineer>=>!!engineer);if(!project||!team.length)return state;const run=evaluateProject(project,team,state.annualSalaryBudget,seed);return{...state,projectRuns:[...state.projectRuns,run],phase:state.projectRuns.length?'DEVELOPMENT_2':'DEVELOPMENT_1'}}
export function revealResult(state:GameState):GameState{const run=state.projectRuns.at(-1);if(!run)return state;return{...state,companyCash:state.companyCash+run.actualReward,annualSalaryBudget:state.annualSalaryBudget+run.salaryBudgetGrowth,selectedProjectId:null,completedProjectIds:[...state.completedProjectIds,run.projectId],phase:state.projectRuns.length===1?'RESULT_1':'RESULT_2'}}
